### ISSUE TITLE
Bug: Phet Sims not displaying in Question Library

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor-js#2379]
PheT sims in physics sections 22.2 and 22.11 homework questions not displaying in question library from teacher view

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/b5bebe3e-acdc-4fba-a8a4-dea79160eb08)

**Comment by nathanstitt** [comment]
Sorry, but I'm unable to locate any sims in the HW builder or section library.

The screenshot shows chapter 22.2 but that content doesn't have any that I see.  Chapter 2.4 does have one in a reading but it's embedded in the content and isn't an exercise, which causes it not to show up in QL/HW builder.

If you can find any please give a login and URL for them and the chapter/section they're in.

**Comment by carlycurran** [comment]
@nathanstitt The Question ID for the Magnets SIM in the original screenshot is ID:7392@7

Hard to find in QL because nothing shows up at all that says SIM!

[Screen Shot 2018-10-12 at 12.05.47 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/6a565f32-2564-4ccb-b7a0-8838339b594d) 

Here's another one from the QL:
![Screen Shot 2018-10-12 at 12.03.26 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/16930888-b1d7-4a19-96a8-2c9b44d2cb5c)

**Comment by nathanstitt** [comment]
hm, so I don't see `7392@7` having a sim.  attached is what it looks like in exercise editor.

It looks to me like this might be a bug with the exercise.  Maybe @lwtchu can investigate further?

![screen shot 2018-10-12 at 12 19 02 pm](https://user-images.githubusercontent.com/79566/46883968-254b5b80-ce19-11e8-8dbe-f8e04c11be79.png)

**Comment by carlycurran** [comment]
@nathanstitt, Larissa says that the tag “requires context - yes” does show up in exercises. SO, the assessment will pull the feature when it’s presented. 

But it looks like it's not showing up in QL view.

**Comment by Malar-Natarajan** [comment]
Verified in QA
