### ISSUE TITLE
Allow MPQs in APUSH

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor-js#2882]
### User Story 
**Brief description:**
Currently, MPQs cannot be assigned by Tutor. So, Tutor-selected questions in a HW assignment cannot be multi-part. The problem is: ALL of the APUSH HW questions are multi-part

**Rationale:**
Tutor-selected assessments is part of “adaptive courseware.” We need to either add non-MPQs to the HW category OR allow the selection of MPQs.

### Acceptance criteria
- This change will only affect APUSH 
- The total questions for each student should be the same and should match the teacher's assigned total.

What do we do when this is not possible?
- Try to go as close as possible to teacher's assigned total without going over
- If a teacher wants to add 2 Tutor-selected questions to her HW assignment, but there are only 3-part questions available, we assign 2 parts of a 3-part question.

- This is about HW only. Do not need to bring these in for RD.

### Acceptance Tests for testrail
- **title**: 
- **categories**:

> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this story.

**Comment by Dantemss** [comment]
Questions for Carly:
- Does an MPQ count for 1 question slot or multiple slots?
- (if only 1 slot) What do we do if all available MPQs are bigger than the number of available slots
- (if only 1 slot) Do we want to (try to) make students to always get the same number of questions total?
- (if multiple slots) which slots have precedence if they need to take over other slots? (1-ago, 5-ago, random-ago?)

**Comment by carlycurran** [comment]
@Dantemss, good questions: 
- An MPQ counts as multiple question slots (so, 2 parts counts as 2 questions)
- We do want students to get the same number of total questions 😬  
- I think 1-ago should have precedence. Do you have thoughts on this?

**Comment by carlycurran** [comment]
The total questions for each student should be the same and should match the teacher's assigned total. 

What do we do when this is not possible?
- try to go as close as possible to teacher's assigned total without going over

what happens when only 3-part avail and teacher assigns 2 questions? 
students get 0

This is about HW only. Do not need to bring these in for RD. 

There is a chance that students will not get the same number of questions. What happens on our score page, where it shows Tutor Q? Does the student with fewer get a dash? or N/A? Would get 19/19 instead of 19/20, but other students would have 20/20.

**Comment by carlycurran** [comment]
Currently MPQs are only allowed in HW core - what teacher selects. 

We will make a rule that MPQs are allowed in HW dynamic ONLY in APUSH.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Production.
